In [3]:
import numpy as np
import pandas as pd
# import sympy
%display typeset

In [4]:
def load_data(state):
    df = pd.read_csv(f'dados_{state}.csv')
    df['date'] = pd.to_datetime(df.date)
#    df.set_index('data', inplace=True)
    return df

In [5]:
dfMX = load_data('Mexico')
dfMX = dfMX[dfMX['location'].str.contains("Mexico")]
ld = len(dfMX)
html(dfMX.tail().to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>iso_code</th>
      <th>continent</th>
      <th>location</th>
      <th>date</th>
      <th>total_cases</th>
      <th>new_cases</th>
      <th>new_cases_smoothed</th>
      <th>total_deaths</th>
      <th>new_deaths</th>
      <th>new_deaths_smoothed</th>
      <th>total_cases_per_million</th>
      <th>new_cases_per_million</th>
      <th>new_cases_smoothed_per_million</th>
      <th>total_deaths_per_million</th>
      <th>new_deaths_per_million</th>
      <th>new_deaths_smoothed_per_million</th>
      <th>reproduction_rate</th>
      <th>icu_patients</th>
      <th>icu_patients_per_million</th>
      <th>hosp_patients</th>
      <th>hosp_patients_per_million</th>
      <th>weekly_icu_admissions</th>
      <th>weekly_icu_admissions_per_million</th>
      <th>weekly_hosp_admissions</th>
      <th>weekly_hosp_admissions_per_million</th>
      <th>total_tests</th>
      <th>new_tests</th>
      <th>total_tests_per_thousand</th>
      <th>new_tests_per_thousand</th>
      <th>new_tests_smoothed</th>
      <th>new_tests_smoothed_per_thousand</th>
      <th>tests_per_case</th>
      <th>positive_rate</th>
      <th>tests_units</th>
      <th>stringency_index</th>
      <th>population</th>
      <th>population_density</th>
      <th>median_age</th>
      <th>aged_65_older</th>
      <th>aged_70_older</th>
      <th>gdp_per_capita</th>
      <th>extreme_poverty</th>
      <th>cardiovasc_death_rate</th>
      <th>diabetes_prevalence</th>
      <th>female_smokers</th>
      <th>male_smokers</th>
      <th>handwashing_facilities</th>
      <th>hospital_beds_per_thousand</th>
      <th>life_expectancy</th>
      <th>human_development_index</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>34283</th>
      <td>MEX</td>
      <td>North America</td>
      <td>Mexico</td>
      <td>2020-11-12</td>
      <td>986177.0</td>
      <td>7646.0</td>
      <td>6078.143</td>
      <td>96430.0</td>
      <td>588.0</td>
      <td>457.429</td>
      <td>7648.770</td>
      <td>59.302</td>
      <td>47.142</td>
      <td>747.909</td>
      <td>4.561</td>
      <td>3.548</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>74.54</td>
      <td>128932753.0</td>
      <td>66.444</td>
      <td>29.3</td>
      <td>6.857</td>
      <td>4.321</td>
      <td>17336.469</td>
      <td>2.5</td>
      <td>152.783</td>
      <td>13.06</td>
      <td>6.9</td>
      <td>21.4</td>
      <td>87.847</td>
      <td>1.38</td>
      <td>75.05</td>
      <td>0.774</td>
    </tr>
    <tr>
      <th>34284</th>
      <td>MEX</td>
      <td>North America</td>
      <td>Mexico</td>
      <td>2020-11-13</td>
      <td>991835.0</td>
      <td>5658.0</td>
      <td>6091.143</td>
      <td>97056.0</td>
      <td>626.0</td>
      <td>469.143</td>
      <td>7692.654</td>
      <td>43.883</td>
      <td>47.243</td>
      <td>752.765</td>
      <td>4.855</td>
      <td>3.639</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>74.54</td>
      <td>128932753.0</td>
      <td>66.444</td>
      <td>29.3</td>
      <td>6.857</td>
      <td>4.321</td>
      <td>17336.469</td>
      <td>2.5</td>
      <td>152.783</td>
      <td>13.06</td>
      <td>6.9</td>
      <td>21.4</td>
      <td>87.847</td>
      <td>1.38</td>
      <td>75.05</td>
      <td>0.774</td>
    </tr>
    <tr>
     

Achando o R0:

In [7]:
var('S E Ia Is R D a ba bs ca cs p q')

(S, E, Ia, Is, R, D, a, ba, bs, ca, cs, p, q)

In [32]:
dsdt = -(bs * Is + ba * Ia) * S
dedt = (bs * Is + ba * Ia) * S - a * E
diadt = p * a * E - ca * Ia
disdt = (1 - p) * a * E - cs * Is
drdt = ca * Ia + cs * q * Is
dddt = cs * (1 - q) * Is

Equilibrios

In [10]:
solve([dsdt, dedt, diadt, disdt, drdt, dddt],[S, E , Ia, Is, R, D])

[[S == r1, E == 0, Ia == 0, Is == 0, R == r2, D == r3]]

In [15]:
jack = jacobian([dsdt, dedt, diadt, disdt, drdt, dddt],[S, E , Ia, Is, R, D])
jack

[-Ia*ba - Is*bs              0          -S*ba          -S*bs              0              0]
[ Ia*ba + Is*bs             -a           S*ba           S*bs              0              0]
[             0            a*p            -ca              0              0              0]
[             0     -a*(p - 1)              0            -cs              0              0]
[             0              0             ca           cs*q              0              0]
[             0              0              0    -cs*(q - 1)              0              0]

In [16]:
cp = jack.characteristic_polynomial()
cp

x^6 + (Ia*ba + Is*bs + a + ca + cs)*x^5 + (-S*a*ba*p + S*a*bs*p + Ia*a*ba + Is*a*bs - S*a*bs + Ia*ba*ca + Is*bs*ca + Ia*ba*cs + Is*bs*cs + a*ca + a*cs + ca*cs)*x^4 + (S*a*bs*ca*p - S*a*ba*cs*p + Ia*a*ba*ca + Is*a*bs*ca - S*a*bs*ca + Ia*a*ba*cs + Is*a*bs*cs + Ia*ba*ca*cs + Is*bs*ca*cs + a*ca*cs)*x^3 + (Ia*a*ba*ca*cs + Is*a*bs*ca*cs)*x^2

Cálculo do $R_0$ analítico:

In [20]:
F_cal = matrix([[-(bs * Is + ba * Ia) * S],[0],[0]])
F_cal

[-(Ia*ba + Is*bs)*S]
[                 0]
[                 0]

In [21]:
V_cal_neg = matrix([[(bs+ba)*E],[a*Is],[a*Ia]])
V_cal_neg

[E*(ba + bs)]
[       Is*a]
[       Ia*a]

In [22]:
V_cal_pos = matrix([[0],[(1-p)*(bs+ba)*E],[p*(bs+ba)*E]])
V_cal_pos

[                   0]
[-E*(ba + bs)*(p - 1)]
[       E*(ba + bs)*p]

In [23]:
V_cal = V_cal_neg-V_cal_pos
V_cal

[               E*(ba + bs)]
[E*(ba + bs)*(p - 1) + Is*a]
[     -E*(ba + bs)*p + Ia*a]

In [25]:
F = jacobian(F_cal(S=1),[E,Is,Ia])
F

[  0 -bs -ba]
[  0   0   0]
[  0   0   0]

In [27]:
V = jacobian(V_cal(S=1),[E,Is,Ia])
V

[          ba + bs                 0                 0]
[(ba + bs)*(p - 1)                 a                 0]
[     -(ba + bs)*p                 0                 a]

$R_0 = p(FV^{-1})$

In [28]:
M = F*V.inverse()

In [29]:
M=M.simplify_full()
M

[-((ba - bs)*p + bs)/a                 -bs/a                 -ba/a]
[                    0                     0                     0]
[                    0                     0                     0]

In [30]:
M.eigenvalues()

[-((ba - bs)*p + bs)/a, 0, 0]

In [31]:
R0=M[0,0].simplify_full()
R0

-((ba - bs)*p + bs)/a

Simulação:

In [ ]:
def model(t, y, params):
    S, E, Is, Ia, R, D = y
    a, ba, bs, ca, cs, p, q = params
    return [
        -lamb * ((1 - chi) * S),  # dS/dt
        lamb * ((1 - chi) * S) - alpha * E,  # dE/dt
        (1 - p) * alpha * E - delta * I - phi * I,  # dI/dt
        p * alpha * E - gamma * A,
        phi * I - (rho + mu) * H,  # dH/dt
        delta * I + rho * H + gamma * A,  # dR/dt
        phi * I,  # (1-p)*alpha*E+ p*alpha*E # Hospit. acumuladas
        mu * H  # Morte acumuladas
    ]